# Site settings
title: Now you see me
SEOTitle: Chao's page
header-img: img/home-bg-1-dark.jpg
email: xuchao653861872@gmail.com
description: "Great to meet you here."
keyword: "Chao, Share"
url: "http://chaoxu0512.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/chaoxu0512/chaoxu0512.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Welcome to visit, I'm Chao Xu!"
sidebar-avatar: /img/avatar_m.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     6590319358
zhihu_username:     jin-tian-ni-chi-nian-gao-liao-yao
github_username:    chaoxu0512
facebook_username:  chao.xu.3517
# jianshu_username:   4097902ff44b
twitter_username:   653861872




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# gems: [jekyll-paginate]
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
syntax_highlighter: rough
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  # syntax_highlighter_opts:
  #   span:
  #     line_numbers: false
  #   block:
  #     line_numbers: true
  #     start_line: 1


# 评论系统
# Disqus（https://disqus.com/）
disqus_username: cx0512

# Gitalk
#gitalk:
#  enable: true    #是否开启Gitalk评论
#  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
#  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
#  repo: qiubaiying.github.io   #仓库名称
#  owner: qiubaiying   #github用户名
#  admin: qiubaiying
#  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-178144024-1'            # Format: UA-xxxxxx-xx
ga_domain: cx0512.com               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true

# Friends
friends: [
    {
        title: "微博",
        href: "https://weibo.com/u/6590319358"
    },{
        title: "知乎",
        href: "https://www.zhihu.com/people/jin-tian-ni-chi-nian-gao-liao-yao"
    }
]
